### ISSUE TITLE
`#TODO`

### ISSUE THREAD

**Issue by NNBnh** [info-mono/diyship#1]
- [x] [Wiki](https://github.com/info-mono/diyship/wiki)
- [x] [Add Nushell support](https://github.com/starship/starship/pull/2847)
- [x] [Add Xonsh support](https://github.com/starship/starship/pull/2807)
